/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all upcoming bookings sorted by startTime */
        get: operations["Bookings_listBookings"];
        put?: never;
        /** @description Book a slot. Returns 409 if the slot is already taken */
        post: operations["Bookings_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types */
        get: operations["EventTypes_listEventTypes"];
        put?: never;
        /** @description Create a new event type */
        post: operations["EventTypes_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get event type by ID */
        get: operations["EventTypes_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Partially update an event type */
        patch: operations["EventTypes_patchEventType"];
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get available slots for the next 14 days */
        get: operations["EventTypes_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A booking made by a guest */
        Booking: {
            id: components["schemas"]["Uuid"];
            eventTypeId: components["schemas"]["Uuid"];
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            guestName: string;
            guestEmail: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Payload to create a new booking */
        BookingCreate: {
            eventTypeId: components["schemas"]["Uuid"];
            /** Format: date-time */
            startTime: string;
            guestName: string;
            guestEmail: string;
        };
        /** @description Error response returned on 4xx failures */
        ErrorResponse: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        /** @description Type of event that can be booked */
        EventType: {
            id: components["schemas"]["Uuid"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Payload to create a new event type */
        EventTypeCreate: {
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Payload to patch an existing event type (all fields optional) */
        EventTypePatch: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /** @enum {string} */
        ServiceVersions: "1.0.0";
        /** @description Available time slot for booking */
        Slot: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
        };
        /**
         * Format: uuid
         * @description UUID identifier
         */
        Uuid: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypes_patchEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypePatch"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypes_getSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
        };
    };
}
